In [1]:
import pandas as pd

In [2]:
dat = pd.read_csv('/mnt/mfs/statgen/UKBiobank/results/ARHI_heritability/pheno_files/090321_UKBB_Hearing_difficulty_f2247_expandedwhite_45502cases_96601ctrl.common50K_PC1_10.greml_pheno', header=0, delim_whitespace=True)

In [3]:
dat

           FID      IID  sex  f2247  ...       PC7       PC8       PC9      PC10
0      1000081  1000081  0.0    0.0  ...  0.008095  0.001342 -0.008544 -0.004842
1      1000331  1000331  1.0    0.0  ...  0.025019 -0.002112  0.014919 -0.017077
2      1000340  1000340  1.0    0.0  ...  0.001163  0.001341  0.001791 -0.001327
3      1000421  1000421  1.0    0.0  ... -0.000936 -0.002476 -0.003586 -0.017104
4      1000439  1000439  1.0    0.0  ... -0.002753  0.003908  0.003017 -0.000270
...        ...      ...  ...    ...  ...       ...       ...       ...       ...
49995  6024762  6024762  1.0    0.0  ...  0.006713 -0.019845 -0.002808 -0.002095
49996  6024812  6024812  0.0    0.0  ... -0.015600  0.009687  0.001769 -0.025690
49997  6025004  6025004  1.0    0.0  ... -0.001699  0.004117 -0.000647  0.014148
49998  6025145  6025145  0.0    0.0  ...  0.026920  0.007369 -0.002309  0.013782
49999  6025346  6025346  1.0    0.0  ...  0.002032 -0.008196  0.009447  0.007725

[50000 rows x 15 columns]

In [11]:
phenoCol=["f2247"]
covarCol=['sex']
qCovarCol=['age']
if len(phenoCol) > 0:
    dat.to_csv(f"/home/dmc2245/f2247.gcta_phenotype", sep=' ', index=False, columns = ['FID', 'IID'] + phenoCol)
dat = pd.read_csv('/mnt/mfs/statgen/UKBiobank/results/ARHI_heritability/pheno_files/090321_UKBB_Hearing_difficulty_f2247_expandedwhite_45502cases_96601ctrl.common50K_PC1_10.greml_pheno', header=0, delim_whitespace=True)
if len(covarCol) > 0:
    dat.to_csv(f"/home/dmc2245/f2247.gcta_covar", sep=' ', index=False, columns = ['FID', 'IID'] + covarCol)
if len(qCovarCol) > 0:
    dat.to_csv(f"/home/dmc2245/f2247.gcta_qcovar", sep=' ', index=False, columns = ['FID', 'IID'] + qCovarCol)

In [4]:
import pandas as pd
import numpy as np

In [5]:
dat = pd.read_csv("/mnt/mfs/statgen/UKBiobank/results/ARHI_heritability/pheno_files/090321_UKBB_Hearing_difficulty_f2247_expandedwhite_45502cases_96601ctrl.common50K_PC1_10.greml_pheno", header=0, delim_whitespace=True, dtype=str)
dat = dat.replace(to_replace =np.nan, value ="NA")

In [6]:
dat

           FID      IID  ...                    PC9                   PC10
0      1000081  1000081  ...   -0.00854446328678576   -0.00484154697201478
1      1000331  1000331  ...     0.0149190670884902    -0.0170765123300426
2      1000340  1000340  ...      0.001791162146612   -0.00132749377131828
3      1000421  1000421  ...    -0.0035856349905142     -0.017103548148085
4      1000439  1000439  ...       0.00301660516127  -0.000270031246005353
...        ...      ...  ...                    ...                    ...
49995  6024762  6024762  ...   -0.00280800487218192   -0.00209484171953615
49996  6024812  6024812  ...    0.00176900555501162     -0.025689896708373
49997  6025004  6025004  ...  -0.000647439335041494     0.0141481259611517
49998  6025145  6025145  ...   -0.00230924716357117      0.013781905831998
49999  6025346  6025346  ...    0.00944729756888285    0.00772467087660684

[50000 rows x 15 columns]

In [ ]:
if len(phenoCol) > 0:    
    dat.to_csv(f"{cwd}/{phenoFile:bn}.regenie_phenotype", sep='\t', index=False, columns = ['FID', 'IID'] + phenoCol)
dat = pd.read_csv(covarFile, header=0, delim_whitespace=True, dtype=str)
if len(covarCol) > 0 or len(qCovarCol) > 0:
    dat = dat.dropna(subset=covarCol)
    dat = dat.dropna(subset=qCovarCol)
    dat.replace(to_replace =np.nan, value ="NA")
    dat1 = pd.DataFrame(dat, columns = ['FID','IID'] + covarCol)
    #dat1 = dat1.astype(int)
    dat2 = pd.DataFrame(dat, columns = ['IID'] + qCovarCol)
    merged_left = pd.merge(left=dat1, right=dat2, how='left', left_on='IID', right_on='IID')
    merged_left.to_csv(f"{cwd}/{phenoFile:bn}.regenie_covar", sep=' ', index=False)