# Permutation for chromsome X burden test

Five targer genes:  PRPS1, POU3F4, SMPX, AIFM1 and COL4A6

Permutation test number: 5000

## Genome

In [2]:
import pandas as pd
file = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/BurdenFiles/All_qced_exome200k_rename_chrX.hg38.hg38_multianno.csv.anno_file"
anno = pd.read_csv(file,sep=" ",header=None)
anno

                         0        1      2
0          chrX:334222:G:A  PPP2R3B  other
1          chrX:334223:C:A  PPP2R3B  other
2          chrX:334224:A:G  PPP2R3B  other
3          chrX:334229:A:C  PPP2R3B  other
4          chrX:334232:C:T  PPP2R3B  other
...                    ...      ...    ...
294817  chrX:155774815:G:C    SPRY3  other
294818  chrX:155774816:G:A    SPRY3  other
294819  chrX:155774828:A:G    SPRY3  other
294820  chrX:155774836:C:G    SPRY3  other
294821  chrX:155774837:A:G    SPRY3  other

[294822 rows x 3 columns]

In [5]:
target = [ "PRPS1", "POU3F4", "SMPX", "AIFM1", "COL4A6"]
anno[anno[1].isin(target)]

                          0      1      2
45946     chrX:21737489:G:A   SMPX  other
45947     chrX:21737501:C:T   SMPX  other
45948     chrX:21737529:G:T   SMPX  other
45949   chrX:21737532:GAT:G   SMPX  other
45950     chrX:21737539:T:G   SMPX  other
...                     ...    ...    ...
226604   chrX:130165715:G:C  AIFM1  other
226605   chrX:130165724:C:G  AIFM1  other
226606   chrX:130165726:T:G  AIFM1  other
226607   chrX:130165732:C:A  AIFM1  other
226608   chrX:130165732:C:G  AIFM1  other

[2432 rows x 3 columns]

In [6]:
anno[anno[1].isin(target)][1].value_counts()

COL4A6    1500
AIFM1      534
PRPS1      173
POU3F4     157
SMPX        68
Name: 1, dtype: int64

In [8]:
anno[anno[1].isin(target)][0].to_csv("~/project/en2509/exome/BurdenTest/permutation/genome/genome_genes.snplist.txt",header=False,index=False)

In [9]:
plink \
--bfile /mnt/vast/hpc/csg/en2509/exome/Both_qced_exome200k \
--extract ~/project/en2509/exome/BurdenTest/permutation/genome/genome_genes.snplist.txt \
--keep-allele-order \
--make-bed \
--out ~/project/en2509/exome/BurdenTest/permutation/genome/genome_genes

PLINK v1.90b6.21 64-bit (19 Oct 2020)          www.cog-genomics.org/plink/1.9/
(C) 2005-2020 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to /home/gl2776/project/en2509/exome/BurdenTest/permutation/genome/genome_genes.log.
Options in effect:
  --bfile /mnt/vast/hpc/csg/en2509/exome/Both_qced_exome200k
  --extract /home/gl2776/project/en2509/exome/BurdenTest/permutation/genome/genome_genes.snplist.txt
  --keep-allele-order
  --make-bed
  --out /home/gl2776/project/en2509/exome/BurdenTest/permutation/genome/genome_genes

128831 MB RAM detected; reserving 64415 MB for main workspace.
Allocated 8597 MB successfully, after larger attempt(s) failed.
98747 variants loaded from .bim file.
187908 people (84401 males, 103507 females) loaded from .fam.
--extract: 752 variants remaining.
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 187908 founders and 0 nonfounders present.
Calculating allele frequencies... 10111213141516171819202122232425262728293031323334353637383940414243444546474849505152535455565758596061626364656667686970717273747576777879808182838485868788899091929394959697989 done.
Warning: 3890 het. haploid genotypes present (see
/home/gl2776/project/en2509/exome/BurdenTest/permutation/genome/genome_genes.hh
); many commands treat these as missing.
Total genotyping rate is 0.995344.
752 variants and 187908 people pass filters and QC.
Note: No phenotypes present.
--make-bed to
/home/gl2776/project/en2509/exome/BurdenTest/permutation/genome/genome_genes.bed
+
/home/gl2776/project/en2509/exome/BurdenTest/permutation/genome/genome_genes.bim
+
/home/gl2776/project/en2509/exome/BurdenTest/permutation/genome/genome_genes.fam
... 101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899done.

## Phenotypes

In [5]:
## Merge all trait phenotype files
import pandas as pd
file = "/mnt/vast/hpc/csg/UKBiobank/phenotype_files/hearing_impairment/090321_UKBB_Hearing_aid_f3393_expandedwhite_6436cases_96601ctrl_PC1_2.tsv"
data1 = pd.read_csv(file,sep="\t",header=0)
file = "/mnt/vast/hpc/csg/UKBiobank/phenotype_files/hearing_impairment/090321_UKBB_Hearing_difficulty_f2247_expandedwhite_45502cases_96601ctrl_PC1_2.tsv"
data2 = pd.read_csv(file,sep="\t",header=0)
file = "/mnt/vast/hpc/csg/UKBiobank/phenotype_files/hearing_impairment/090321_UKBB_Hearing_noise_f2257_expandedwhite_65660cases_96601ctrl_PC1_2.tsv"
data3 = pd.read_csv(file,sep="\t",header=0)
file = "/mnt/vast/hpc/csg/UKBiobank/phenotype_files/hearing_impairment/090321_UKBB_Combined_f2247_f2257_expandedwhite_38410cases_96601ctrl_PC1_2.tsv"
data4 = pd.read_csv(file,sep="\t",header=0)

In [35]:
data1

            FID      IID  sex  f3393  age       PC1       PC2
0       1000078  1000078    1      0   60  0.007025  0.009615
1       1000081  1000081    0      0   67 -0.119832 -0.012082
2       1000224  1000224    1      0   58  0.002236 -0.012769
3       1000236  1000236    0      0   70 -0.002966  0.016806
4       1000255  1000255    1      0   61  0.004213  0.002939
...         ...      ...  ...    ...  ...       ...       ...
103032  6025251  6025251    0      0   56  0.003574 -0.008428
103033  6025319  6025319    1      0   56  0.007400 -0.003109
103034  6025346  6025346    1      0   53 -0.000531  0.010010
103035  6025363  6025363    0      0   64  0.005168 -0.007066
103036  6025411  6025411    1      0   49  0.015188 -0.007733

[103037 rows x 7 columns]

In [4]:
data1["FID"].equals(data1["IID"])

True

In [6]:
union = data1[["IID","f3393"]].merge(data2[["IID","f2247"]], how = "outer", left_on = "IID", right_on = "IID", sort=True)
union = union.merge(data3[["IID","f2257"]], how = "outer", left_on = "IID", right_on = "IID", sort=True)
union = union.merge(data4[["IID","f2247_f2257"]], how = "outer", left_on = "IID", right_on = "IID", sort=True)
union

            IID  f3393  f2247  f2257  f2247_f2257
0       1000035    NaN    NaN    1.0          NaN
1       1000078    0.0    0.0    0.0          0.0
2       1000081    0.0    0.0    0.0          0.0
3       1000198    NaN    1.0    1.0          1.0
4       1000224    0.0    0.0    0.0          0.0
...         ...    ...    ...    ...          ...
169447  6025251    0.0    0.0    0.0          0.0
169448  6025319    0.0    0.0    0.0          0.0
169449  6025346    0.0    0.0    0.0          0.0
169450  6025363    0.0    0.0    0.0          0.0
169451  6025411    0.0    0.0    0.0          0.0

[169452 rows x 5 columns]

In [18]:
len(set(data1["IID"]).union(data2["IID"],data3["IID"],data4["IID"]))

169452

In [7]:
import numpy as np
union.replace(to_replace =np.nan, value ="NA", inplace=True)
union

            IID f3393 f2247 f2257 f2247_f2257
0       1000035    NA    NA   1.0          NA
1       1000078   0.0   0.0   0.0         0.0
2       1000081   0.0   0.0   0.0         0.0
3       1000198    NA   1.0   1.0         1.0
4       1000224   0.0   0.0   0.0         0.0
...         ...   ...   ...   ...         ...
169447  6025251   0.0   0.0   0.0         0.0
169448  6025319   0.0   0.0   0.0         0.0
169449  6025346   0.0   0.0   0.0         0.0
169450  6025363   0.0   0.0   0.0         0.0
169451  6025411   0.0   0.0   0.0         0.0

[169452 rows x 5 columns]

In [8]:
union["FID"] = union["IID"]
union = union[["FID", 'IID', 'f3393', 'f2247', 'f2257', 'f2247_f2257']]
union

            FID      IID f3393 f2247 f2257 f2247_f2257
0       1000035  1000035    NA    NA   1.0          NA
1       1000078  1000078   0.0   0.0   0.0         0.0
2       1000081  1000081   0.0   0.0   0.0         0.0
3       1000198  1000198    NA   1.0   1.0         1.0
4       1000224  1000224   0.0   0.0   0.0         0.0
...         ...      ...   ...   ...   ...         ...
169447  6025251  6025251   0.0   0.0   0.0         0.0
169448  6025319  6025319   0.0   0.0   0.0         0.0
169449  6025346  6025346   0.0   0.0   0.0         0.0
169450  6025363  6025363   0.0   0.0   0.0         0.0
169451  6025411  6025411   0.0   0.0   0.0         0.0

[169452 rows x 6 columns]

In [30]:
union.to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.phe.txt",sep="\t",index=False)

In [33]:
union[["FID", 'IID']].to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.phe.id.txt",sep="\t",index=False)

In [34]:
union[['f3393', 'f2247', 'f2257', 'f2247_f2257']].to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.phe.phenotypes.txt",sep="\t",index=False)

In [9]:
# covariates
## f3393
cover = union[["FID", 'IID']].merge(data1[["IID","sex","age","PC1","PC2"]], how="left",left_on="IID",right_on="IID")
cover.replace(to_replace =np.nan, value ="NA", inplace=True)
cover

            FID      IID  sex   age       PC1       PC2
0       1000035  1000035   NA    NA        NA        NA
1       1000078  1000078  1.0  60.0  0.007025  0.009615
2       1000081  1000081  0.0  67.0 -0.119832 -0.012082
3       1000198  1000198   NA    NA        NA        NA
4       1000224  1000224  1.0  58.0  0.002236 -0.012769
...         ...      ...  ...   ...       ...       ...
169447  6025251  6025251  0.0  56.0  0.003574 -0.008428
169448  6025319  6025319  1.0  56.0    0.0074 -0.003109
169449  6025346  6025346  1.0  53.0 -0.000531   0.01001
169450  6025363  6025363  0.0  64.0  0.005168 -0.007066
169451  6025411  6025411  1.0  49.0  0.015188 -0.007733

[169452 rows x 6 columns]

In [10]:
cover[["sex","age","PC1","PC2"]].to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.covar.f3393",sep="\t",index=False)
cover[["FID", 'IID',"sex","age","PC1","PC2"]].to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.covar.origin.f3393.txt",sep="\t",index=False)

In [11]:
## f2247
cover = union[["FID", 'IID']].merge(data2[["IID","sex","age","PC1","PC2"]], how="left",left_on="IID",right_on="IID")
cover.replace(to_replace =np.nan, value ="NA", inplace=True)
cover[["sex","age","PC1","PC2"]].to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.covar.f2247",sep="\t",index=False)
cover[["FID", 'IID', "sex","age","PC1","PC2"]].to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.covar.origin.f2247.txt",sep="\t",index=False)
## f2257
cover = union[["FID", 'IID']].merge(data3[["IID","sex","age","PC1","PC2"]], how="left",left_on="IID",right_on="IID")
cover.replace(to_replace =np.nan, value ="NA", inplace=True)
cover[["sex","age","PC1","PC2"]].to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.covar.f2257",sep="\t",index=False)
cover[["FID", 'IID', "sex","age","PC1","PC2"]].to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.covar.origin.f2257.txt",sep="\t",index=False)
## f2247_f2257
cover = union[["FID", 'IID']].merge(data4[["IID","sex","age","PC1","PC2"]], how="left",left_on="IID",right_on="IID")
cover.replace(to_replace =np.nan, value ="NA", inplace=True)
cover[["sex","age","PC1","PC2"]].to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.covar.f2247_f2257",sep="\t",index=False)
cover[["FID", 'IID', "sex","age","PC1","PC2"]].to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.covar.origin.f2247_f2257.txt",sep="\t",index=False)

## Regenie burden permutation

In [12]:
# Common variables Columbia's cluster
UKBB_PATH=$HOME/UKBiobank
UKBB_yale=$HOME/UKBiobank_Yale_transfer
USER_PATH=$HOME/working
container_lmm=$HOME/containers/lmm.sif
container_marp=$HOME/containers/marp.sif
container_annovar=$HOME/containers/gatk4-annovar.sif
hearing_pheno_path=$UKBB_PATH/phenotype_files/hearing_impairment
tpl_file=$USER_PATH/bioworkflows/admin/csg.yml
formatFile_fastgwa=$USER_PATH/UKBB_GWAS_dev/data/fastGWA_template.yml
formatFile_bolt=$USER_PATH/UKBB_GWAS_dev/data/boltlmm_template.yml
formatFile_saige=$USER_PATH/UKBB_GWAS_dev/data/saige_template.yml
formatFile_regenie=$USER_PATH/UKBB_GWAS_dev/data/regenie_template.yml

# Workflows
lmm_sos=$USER_PATH/bioworkflows/GWAS/LMM.ipynb
anno_sos=$USER_PATH/bioworkflows/variant-annotation/annovar.ipynb
clumping_sos=$USER_PATH/bioworkflows/GWAS/LD_Clumping.ipynb
extract_sos=$USER_PATH/bioworkflows/GWAS/Region_Extraction.ipynb
snptogene_sos=$USER_PATH/UKBB_GWAS_dev/workflow/snptogene.ipynb

### Original regenie with the merged phenotypes

In [20]:
# f3393
trait=f3393
lmm_dir_regenie=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/$trait
lmm_sbatch_regenie="$lmm_dir_regenie/$trait-$(date +"%Y-%m-%d").sbatch"
phenoFile=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.phe.txt
covarFile=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.covar.origin.$trait.txt
phenoCol=$trait
covarCol=sex
qCovarCol='age PC1 PC2'
genoFile=/mnt/vast/hpc/csg/en2509/exome/Both_qced_exome200k.bed
bfile=/mnt/vast/hpc/csg/en2509/exome/output/Female_f2247/UKB_chrX_EU_Unrealted_Indiv.bed
anno_file=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/BurdenFiles/All_qced_exome200k_rename_chrX.hg38.hg38_multianno.csv.anno_file
set_list=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/BurdenFiles/All_qced_exome200k_rename_chrX.hg38.hg38_multianno.csv.set_list_file
mask_file=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/BurdenFiles/All_qced_exome200k_rename_chrX.hg38.hg38_multianno.csv.mask_file
aaf_file=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/BurdenFiles/All_qced_exome200k_rename_chrX.hg38.hg38_multianno.csv.aff_file
snpannofile=/mnt/mfs/statgen/UKBiobank/results/ukb23155_200Kexomes_annovar/2021_10_12_hg38_exome/ukb23155_chr1_chr22_091321.hg38.hg38_multianno.renamedcols.csv.gz
build_mask=max
aaf_bins='0.005 0.01'
tpl_file=~/working/bioworkflows/admin/csg.yml
lmm_sos=~/working/bioworkflows/GWAS/LMM.ipynb
container_marp=~/containers/marp.sif
container_lmm=~/containers/lmm.sif
lmm_job_size=1
ylim=10
reverse_log_p=True
numThreads=20
formatFile_regenie=~/working/UKBB_GWAS_dev/data/regenie_template.yml
bsize=1000
trait=bt
minMAC=1


lmm_args="""regenie_burden
    --cwd $lmm_dir_regenie 
    --bfile $bfile 
    --genoFile $genoFile
    --phenoFile $phenoFile 
    --covarFile $covarFile
    --formatFile $formatFile_regenie 
    --phenoCol $phenoCol
    --covarCol $covarCol  
    --qCovarCol $qCovarCol
    --bsize $bsize
    --trait $trait
    --anno_file $anno_file
    --set_list $set_list
    --mask_file $mask_file
    --aaf_file $aaf_file
    --aaf_bins $aaf_bins
    --build_mask $build_mask
    --job_size $lmm_job_size
    --ylim $ylim
    --reverse_log_p $reverse_log_p
    --numThreads $numThreads
    --minMAC $minMAC
    --snpannofile $snpannofile
    --container_lmm $container_lmm
    --container_marp $container_marp
"""

sos run ~/working/UKBB_GWAS_dev/admin/Get_Job_Script.ipynb csg \
    --template-file $tpl_file \
    --workflow-file $lmm_sos \
    --to-script $lmm_sbatch_regenie \
    --args "$lmm_args"

# f2247
trait=f2247
lmm_dir_regenie=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/$trait
lmm_sbatch_regenie="$lmm_dir_regenie/$trait-$(date +"%Y-%m-%d").sbatch"
phenoFile=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.phe.txt
covarFile=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.covar.origin.$trait.txt
phenoCol=$trait

lmm_args="""regenie_burden
    --cwd $lmm_dir_regenie 
    --bfile $bfile 
    --genoFile $genoFile
    --phenoFile $phenoFile 
    --covarFile $covarFile
    --formatFile $formatFile_regenie 
    --phenoCol $phenoCol
    --covarCol $covarCol  
    --qCovarCol $qCovarCol
    --bsize $bsize
    --trait $trait
    --anno_file $anno_file
    --set_list $set_list
    --mask_file $mask_file
    --aaf_file $aaf_file
    --aaf_bins $aaf_bins
    --build_mask $build_mask
    --job_size $lmm_job_size
    --ylim $ylim
    --reverse_log_p $reverse_log_p
    --numThreads $numThreads
    --minMAC $minMAC
    --snpannofile $snpannofile
    --container_lmm $container_lmm
    --container_marp $container_marp
"""

sos run ~/working/UKBB_GWAS_dev/admin/Get_Job_Script.ipynb csg \
    --template-file $tpl_file \
    --workflow-file $lmm_sos \
    --to-script $lmm_sbatch_regenie \
    --args "$lmm_args"

# f2257
trait=f2257
lmm_dir_regenie=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/$trait
lmm_sbatch_regenie="$lmm_dir_regenie/$trait-$(date +"%Y-%m-%d").sbatch"
phenoFile=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.phe.txt
covarFile=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.covar.origin.$trait.txt
phenoCol=$trait

lmm_args="""regenie_burden
    --cwd $lmm_dir_regenie 
    --bfile $bfile 
    --genoFile $genoFile
    --phenoFile $phenoFile 
    --covarFile $covarFile
    --formatFile $formatFile_regenie 
    --phenoCol $phenoCol
    --covarCol $covarCol  
    --qCovarCol $qCovarCol
    --bsize $bsize
    --trait $trait
    --anno_file $anno_file
    --set_list $set_list
    --mask_file $mask_file
    --aaf_file $aaf_file
    --aaf_bins $aaf_bins
    --build_mask $build_mask
    --job_size $lmm_job_size
    --ylim $ylim
    --reverse_log_p $reverse_log_p
    --numThreads $numThreads
    --minMAC $minMAC
    --snpannofile $snpannofile
    --container_lmm $container_lmm
    --container_marp $container_marp
"""

sos run ~/working/UKBB_GWAS_dev/admin/Get_Job_Script.ipynb csg \
    --template-file $tpl_file \
    --workflow-file $lmm_sos \
    --to-script $lmm_sbatch_regenie \
    --args "$lmm_args"

# f2247_f2257
trait=f2247_f2257
lmm_dir_regenie=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/$trait
lmm_sbatch_regenie="$lmm_dir_regenie/$trait-$(date +"%Y-%m-%d").sbatch"
phenoFile=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.phe.txt
covarFile=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.covar.origin.$trait.txt
phenoCol=$trait

lmm_args="""regenie_burden
    --cwd $lmm_dir_regenie 
    --bfile $bfile 
    --genoFile $genoFile
    --phenoFile $phenoFile 
    --covarFile $covarFile
    --formatFile $formatFile_regenie 
    --phenoCol $phenoCol
    --covarCol $covarCol  
    --qCovarCol $qCovarCol
    --bsize $bsize
    --trait $trait
    --anno_file $anno_file
    --set_list $set_list
    --mask_file $mask_file
    --aaf_file $aaf_file
    --aaf_bins $aaf_bins
    --build_mask $build_mask
    --job_size $lmm_job_size
    --ylim $ylim
    --reverse_log_p $reverse_log_p
    --numThreads $numThreads
    --minMAC $minMAC
    --snpannofile $snpannofile
    --container_lmm $container_lmm
    --container_marp $container_marp
"""

sos run ~/working/UKBB_GWAS_dev/admin/Get_Job_Script.ipynb csg \
    --template-file $tpl_file \
    --workflow-file $lmm_sos \
    --to-script $lmm_sbatch_regenie \
    --args "$lmm_args"

INFO: Running csg: Configuration for Columbia csg partition cluster
INFO: csg is completed.
INFO: csg output:   /mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/f3393/f3393-2022-07-18.sbatch
INFO: Workflow csg (ID=w2fbd85a4e1b34ac9) is executed successfully with 1 completed step.
INFO: Running csg: Configuration for Columbia csg partition cluster
INFO: csg is completed.
INFO: csg output:   /mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/f2247/f2247-2022-07-18.sbatch
INFO: Workflow csg (ID=w549f34f8e221991e) is executed successfully with 1 completed step.
INFO: Running csg: Configuration for Columbia csg partition cluster
INFO: csg is completed.
INFO: csg output:   /mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/f2257/f2257-2022-07-18.sbatch
INFO: Workflow csg (ID=wc7867644f87d0b4e) is executed successfully with 1 completed step.
INFO: Running csg: Configuration for Columbia csg partition cluster
INFO: csg is completed.
INFO: csg output:   /mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/f2247_f2257/f2247_f2257-2022-07-18.sbatch
INFO: Workflow csg (ID=w275e8d9e52dc4e28) is executed successfully with 1 completed step.

### Permutation each trait

In [24]:
# Use the origin preds
## f3393
trait=f3393
frompath=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/$trait
topath=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/
file=$frompath/*.regenie_pred.list
cp $file $topath/$trait.regenie_pred.list
## f2247
trait=f2247
frompath=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/$trait
topath=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/
file=$frompath/*.regenie_pred.list
cp $file $topath/$trait.regenie_pred.list
## f2257
trait=f2257
frompath=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/$trait
topath=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/
file=$frompath/*.regenie_pred.list
cp $file $topath/$trait.regenie_pred.list
cp $file $topath
## f2247_f2257
trait=f2247_f2257
frompath=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/$trait
topath=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/
file=$frompath/*.regenie_pred.list
cp $file $topath/$trait.regenie_pred.list

In [23]:
lmm_dir_regenie=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/
lmm_sbatch_regenie=$lmm_dir_regenie/permutation-regenie-burden_$(date +"%Y-%m-%d").sbatch
phenoCol="f3393 f2247 f2257 f2247_f2257"
covarCol=sex
qCovarCol='age PC1 PC2'
bfile=/mnt/vast/hpc/csg/en2509/exome/output/Female_f2247/UKB_chrX_EU_Unrealted_Indiv.bed \
genoFile=/mnt/vast/hpc/csg/en2509/exome/Both_qced_exome200k.bed \
anno_file=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/BurdenFiles/All_qced_exome200k_rename_chrX.hg38.hg38_multianno.csv.anno_file
set_list=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/BurdenFiles/All_qced_exome200k_rename_chrX.hg38.hg38_multianno.csv.set_list_file
mask_file=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/BurdenFiles/All_qced_exome200k_rename_chrX.hg38.hg38_multianno.csv.mask_file
aaf_file=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/BurdenFiles/All_qced_exome200k_rename_chrX.hg38.hg38_multianno.csv.aff_file
build_mask=max
aaf_bins='0.005 0.01'
tpl_file=~/working/bioworkflows/admin/csg.yml
lmm_sos=~/working/Ghana/Reg.ipynb
container_marp=~/containers/marp.sif
container_lmm=~/containers/lmm.sif
lmm_job_size=1
ylim=10
reverse_log_p=True
numThreads=1
formatFile_regenie=~/working/UKBB_GWAS_dev/data/regenie_template.yml
bsize=1000
trait=bt
minMAC=1
id_column=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.phe.id.txt
pheno_column=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.phe.phenotypes.txt
covar_column=/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/phenotype/merged.covar
idstart=1
idend=5000

lmm_args="""regenie_burden_permutation
    --cwd $lmm_dir_regenie 
    --bfile $bfile 
    --genoFile $genoFile
    --phenoFile $phenoFile 
    --formatFile $formatFile_regenie 
    --phenoCol $phenoCol
    --covarCol $covarCol  
    --qCovarCol $qCovarCol
    --bsize $bsize
    --trait $trait
    --anno_file $anno_file
    --set_list $set_list
    --mask_file $mask_file
    --aaf_file $aaf_file
    --aaf_bins $aaf_bins
    --build_mask $build_mask
    --job_size $lmm_job_size
    --ylim $ylim
    --reverse_log_p $reverse_log_p
    --numThreads $numThreads
    --minMAC $minMAC
    --container_lmm $container_lmm
    --container_marp $container_marp
    --id_column $id_column
    --pheno_column $pheno_column 
    --covar_column $covar_column
    --idstart $idstart
    --idend $idend
"""

sos run ~/working/UKBB_GWAS_dev/admin/Get_Job_Script.ipynb csg \
    --template-file $tpl_file \
    --workflow-file $lmm_sos \
    --to-script $lmm_sbatch_regenie \
    --args "$lmm_args"

INFO: Running csg: Configuration for Columbia csg partition cluster
INFO: csg is completed.
INFO: csg output:   /mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/permutation-regenie-burden_2022-07-18.sbatch
INFO: Workflow csg (ID=w6df807d5ed90513d) is executed successfully with 1 completed step.

## Results

### Burden each trait

In [2]:
ls -1U /mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache | grep .gz | wc -l

20000

In [3]:
ls -1U /mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache | grep .gz | head

permutation.1000_burden_f2247.regenie.gz
permutation.1000_burden_f2247_f2257.regenie.gz
permutation.1000_burden_f2257.regenie.gz
permutation.1000_burden_f3393.regenie.gz
permutation.1001_burden_f2247.regenie.gz
permutation.1001_burden_f2247_f2257.regenie.gz
permutation.1001_burden_f2257.regenie.gz
permutation.1001_burden_f3393.regenie.gz
permutation.1002_burden_f2247.regenie.gz
permutation.1002_burden_f2247_f2257.regenie.gz
grep: write error: Broken pipe
ls: write error: Broken pipe

In [2]:
## Original burden test results 
### Mask2.0.01
import pandas as pd
import os
data = pd.read_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/f3393/merged.phe_f3393.regenie_burden.snp_stats_original_columns.gz",compression = "gzip",sep="\t",header=0)
data

,CHROM,GENPOS,ID,ALLELE0,ALLELE1,A1FREQ,N,TEST,BETA,SE,CHISQ,LOG10P,EXTRA
0,23,128050980,ACTRT1.Mask1.singleton,ref,Mask1.singleton,0.000015,68883,ADD,-1.129990,2.216930,0.259804,0.214489,NaN
1,23,136308782,ADGRG4.Mask1.singleton,ref,Mask1.singleton,0.000051,68884,ADD,1.038330,1.483780,0.489704,0.315101,NaN
2,23,116172181,AGTR2.Mask1.singleton,ref,Mask1.singleton,0.000015,68879,ADD,-1.163110,2.702380,0.185246,0.175937,NaN
3,23,85003818,APOOL.Mask1.singleton,ref,Mask1.singleton,0.000007,68579,ADD,-1.028630,5.691130,0.0326676,0.067237,NaN
4,23,47562899,ARAF.Mask1.singleton,ref,Mask1.singleton,0.000007,68884,ADD,8.959700,3.175760,TEST_FAIL,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3041,23,135287104,ZNF75D.Mask2.0.01,ref,Mask2.0.01,0.003687,68883,ADD,-0.217697,0.165399,1.73235,0.725586,NaN
3042,23,47846187,ZNF81.Mask2.0.01,ref,Mask2.0.01,0.015192,68884,ADD,0.035089,0.077947,0.202646,0.185357,NaN
3043,23,15790398,ZRSR2.Mask2.0.01,ref,Mask2.0.01,0.003687,68884,ADD,-0.268310,0.176898,2.30051,0.888296,NaN
3044,23,57907929,ZXDA.Mask2.0.01,ref,Mask2.0.01,0.014082,68884,ADD,-0.053665,0.083804,0.410063,0.282382,NaN
3045,23,57591952,ZXDB.Mask2.0.01,ref,Mask2.0.01,0.007788,68884,ADD,-0.043922,0.118491,0.1374,0.148204,NaN

In [42]:
def find_target(row):
    for gene in ["PRPS1", "POU3F4", "SMPX", "AIFM1", "COL4A6"]:
        if gene in row["ID"]:
            return True
    return False
data[data.apply(find_target,axis=1)]

,CHROM,GENPOS,ID,ALLELE0,ALLELE1,A1FREQ,N,TEST,BETA,SE,CHISQ,LOG10P,EXTRA
27,23,108156906,COL4A6.Mask1.singleton,ref,Mask1.singleton,0.000029,68884,ADD,-1.153610,1.973660,0.341641,0.252679,NaN
216,23,108156906,COL4A6.Mask1.0.005,ref,Mask1.0.005,0.000167,68884,ADD,-0.712012,0.743900,0.916107,0.470442,NaN
442,23,21737489,SMPX.Mask1.0.005,ref,Mask1.0.005,0.000029,68695,ADD,1.086830,1.514380,0.515055,0.325177,NaN
586,23,108156906,COL4A6.Mask1.0.01,ref,Mask1.0.01,0.000167,68884,ADD,-0.712012,0.743900,0.916107,0.470442,NaN
812,23,21737489,SMPX.Mask1.0.01,ref,Mask1.0.01,0.000029,68695,ADD,1.086830,1.514380,0.515055,0.325177,NaN
901,23,130129507,AIFM1.Mask2.singleton,ref,Mask2.singleton,0.000123,68884,ADD,-1.183100,1.128560,1.09899,0.530932,NaN
1008,23,108156906,COL4A6.Mask2.singleton,ref,Mask2.singleton,0.000240,68884,ADD,0.351857,0.708512,0.246625,0.207986,NaN
1339,23,83508225,POU3F4.Mask2.singleton,ref,Mask2.singleton,0.000073,68884,ADD,-1.080480,1.562040,0.478465,0.310586,NaN
1348,23,107628536,PRPS1.Mask2.singleton,ref,Mask2.singleton,0.000015,68884,ADD,-1.036350,3.966060,0.0682809,0.100258,NaN
1429,23,21737489,SMPX.Mask2.singleton,ref,Mask2.singleton,0.000007,68720,ADD,-0.999783,12.967300,0.00594442,0.027545,NaN
1597,23,130129507,AIFM1.Mask2.0.005,ref,Mask2.0.005,0.001495,68884,ADD,0.510688,0.316135,2.60955,0.973787,NaN
1704,23,108156906,COL4A6.Mask2.0.005,ref,Mask2.0.005,0.017827,68884,ADD,0.093262,0.075421,1.52908,0.665044,NaN
2053,23,83508225,POU3F4.Mask2.0.005,ref,Mask2.0.005,0.000356,68884,ADD,0.990547,0.427360,4.49779,1.469300,NaN
2062,23,107628536,PRPS1.Mask2.0.005,ref,Mask2.0.005,0.000044,68884,ADD,-1.056460,2.118720,0.248632,0.208983,NaN
2150,23,21737489,SMPX.Mask2.0.005,ref,Mask2.0.005,0.000094,68884,ADD,1.310360,0.917184,2.04111,0.815032,NaN
2326,23,130129507,AIFM1.Mask2.0.01,ref,Mask2.0.01,0.001495,68884,ADD,0.510688,0.316135,2.60955,0.973787,NaN
2433,23,108156906,COL4A6.Mask2.0.01,ref,Mask2.0.01,0.027670,68884,ADD,0.097066,0.060124,2.60643,0.972932,NaN
2783,23,83508225,POU3F4.Mask2.0.01,ref,Mask2.0.01,0.000356,68884,ADD,0.990547,0.427360,4.49779,1.469300,NaN
2792,23,107628536,PRPS1.Mask2.0.01,ref,Mask2.0.01,0.000044,68884,ADD,-1.056460,2.118720,0.248632,0.208983,NaN
2880,23,21737489,SMPX.Mask2.0.01,ref,Mask2.0.01,0.000094,68884,ADD,1.310360,0.917184,2.04111,0.815032,NaN

In [3]:
target = ["PRPS1.Mask2.0.01","POU3F4.Mask2.0.01","SMPX.Mask2.0.01","AIFM1.Mask2.0.01","COL4A6.Mask2.0.01"]
data[data["ID"].isin(target)]

,CHROM,GENPOS,ID,ALLELE0,ALLELE1,A1FREQ,N,TEST,BETA,SE,CHISQ,LOG10P,EXTRA
2326,23,130129507,AIFM1.Mask2.0.01,ref,Mask2.0.01,0.001495,68884,ADD,0.510688,0.316135,2.60955,0.973787,NaN
2433,23,108156906,COL4A6.Mask2.0.01,ref,Mask2.0.01,0.027670,68884,ADD,0.097066,0.060124,2.60643,0.972932,NaN
2783,23,83508225,POU3F4.Mask2.0.01,ref,Mask2.0.01,0.000356,68884,ADD,0.990547,0.427360,4.49779,1.469300,NaN
2792,23,107628536,PRPS1.Mask2.0.01,ref,Mask2.0.01,0.000044,68884,ADD,-1.056460,2.118720,0.248632,0.208983,NaN
2880,23,21737489,SMPX.Mask2.0.01,ref,Mask2.0.01,0.000094,68884,ADD,1.310360,0.917184,2.04111,0.815032,NaN

In [4]:
result = data[data["ID"].isin(target)][["CHROM","GENPOS","ID"]].copy()
result

      CHROM     GENPOS                 ID
2326     23  130129507   AIFM1.Mask2.0.01
2433     23  108156906  COL4A6.Mask2.0.01
2783     23   83508225  POU3F4.Mask2.0.01
2792     23  107628536   PRPS1.Mask2.0.01
2880     23   21737489    SMPX.Mask2.0.01

In [5]:
#data = pd.read_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/f3393/merged.phe_f3393.regenie_burden.snp_stats_original_columns.gz",compression = "gzip",sep="\t",header=0)
result = result.merge(data[["ID","LOG10P"]],left_on="ID",right_on="ID",how="inner")
result = result.rename(columns={"LOG10P":"f3393"})
result["f3393"] = 10**(-result[["f3393"]]) 
result

   CHROM     GENPOS                 ID     f3393
0     23  130129507   AIFM1.Mask2.0.01  0.106222
1     23  108156906  COL4A6.Mask2.0.01  0.106431
2     23   83508225  POU3F4.Mask2.0.01  0.033939
3     23  107628536   PRPS1.Mask2.0.01  0.618041
4     23   21737489    SMPX.Mask2.0.01  0.153097

In [6]:
data = pd.read_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/f2247/merged.phe_f2247.regenie_burden.snp_stats_original_columns.gz",compression = "gzip",sep="\t",header=0)
result = result.merge(data[["ID","LOG10P"]],left_on="ID",right_on="ID",how="inner")
result = result.rename(columns={"LOG10P":"f2247"})
result["f2247"] = 10**(-result[["f2247"]]) 
data = pd.read_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/f2257/merged.phe_f2257.regenie_burden.snp_stats_original_columns.gz",compression = "gzip",sep="\t",header=0)
result = result.merge(data[["ID","LOG10P"]],left_on="ID",right_on="ID",how="inner")
result = result.rename(columns={"LOG10P":"f2257"})
result["f2257"] = 10**(-result[["f2257"]]) 
data = pd.read_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/f2247_f2257/merged.phe_f2247_f2257.regenie_burden.snp_stats_original_columns.gz",compression = "gzip",sep="\t",header=0)
result = result.merge(data[["ID","LOG10P"]],left_on="ID",right_on="ID",how="inner")
result = result.rename(columns={"LOG10P":"f2247_f2257"})
result["f2247_f2257"] = 10**(-result[["f2247_f2257"]]) 
result

,CHROM,GENPOS,ID,f3393,f2247,f2257,f2247_f2257
0,23,130129507,AIFM1.Mask2.0.01,0.106222,0.141442,0.071084,0.076015
1,23,108156906,COL4A6.Mask2.0.01,0.106431,0.448032,0.429358,0.734177
2,23,83508225,POU3F4.Mask2.0.01,0.033939,0.126706,0.024993,0.286156
3,23,107628536,PRPS1.Mask2.0.01,0.618041,0.537899,0.343114,0.380426
4,23,21737489,SMPX.Mask2.0.01,0.153097,0.002454,0.000921,0.000830

In [7]:
origin = result

In [11]:
pheno = "f3393"
num_perm = 5000
path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache"
list0 = os.listdir(path)
filelist = []
for file in list0:
    if file.endswith(pheno+".regenie.gz"):
        filelist.append(file)
sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
result = origin[["CHROM","GENPOS","ID",pheno]].copy()
result.loc[result["ID"].isin(sigsnp),"counts"]=0
result.loc[~result["ID"].isin(sigsnp),"counts"]=pd.NA
for file in filelist:
    data=pd.read_csv(os.path.join(path, file),header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if not len(origin.loc[origin["ID"]==snp,pheno])==0 and (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (pd.isna(origin.loc[origin["ID"]==snp,pheno]).values[0]==False):
            count = 1 if (10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True)))<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result.loc[result["ID"]==snp,"counts"] = result.loc[result["ID"]==snp,"counts"] + count
result["counts"] = result["counts"]/num_perm
result.to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/"+pheno+".perm.p.csv",index=False)
result

   CHROM     GENPOS                 ID     f3393  counts
0     23  130129507   AIFM1.Mask2.0.01  0.106222    <NA>
1     23  108156906  COL4A6.Mask2.0.01  0.106431    <NA>
2     23   83508225  POU3F4.Mask2.0.01  0.033939  0.0226
3     23  107628536   PRPS1.Mask2.0.01  0.618041    <NA>
4     23   21737489    SMPX.Mask2.0.01  0.153097    <NA>

In [57]:
pheno = "f2247"
num_perm = 5000
path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache"
list0 = os.listdir(path)
filelist = []
for file in list0:
    if file.endswith(pheno+".regenie.gz"):
        filelist.append(file)
sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
result = origin[["CHROM","GENPOS","ID",pheno]].copy()
result.loc[result["ID"].isin(sigsnp),"counts"]=0
result.loc[~result["ID"].isin(sigsnp),"counts"]=pd.NA
for file in filelist:
    data=pd.read_csv(os.path.join(path, file),header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if not len(origin.loc[origin["ID"]==snp,pheno])==0 and (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (pd.isna(origin.loc[origin["ID"]==snp,pheno]).values[0]==False):
            count = 1 if (10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True)))<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result.loc[result["ID"]==snp,"counts"] = result.loc[result["ID"]==snp,"counts"] + count
result["counts"] = result["counts"]/num_perm
result.to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/"+pheno+".perm.p.csv",index=False)
result

   CHROM     GENPOS                 ID     f2247  counts
0     23  130129507   AIFM1.Mask2.0.01  0.141442    <NA>
1     23  108156906  COL4A6.Mask2.0.01  0.448032    <NA>
2     23   83508225  POU3F4.Mask2.0.01  0.126706    <NA>
3     23  107628536   PRPS1.Mask2.0.01  0.537899    <NA>
4     23   21737489    SMPX.Mask2.0.01  0.002454  0.0012

In [58]:
pheno = "f2257"
num_perm = 5000
path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache"
list0 = os.listdir(path)
filelist = []
for file in list0:
    if file.endswith(pheno+".regenie.gz"):
        filelist.append(file)
sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
result = origin[["CHROM","GENPOS","ID",pheno]].copy()
result.loc[result["ID"].isin(sigsnp),"counts"]=0
result.loc[~result["ID"].isin(sigsnp),"counts"]=pd.NA
for file in filelist:
    data=pd.read_csv(os.path.join(path, file),header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if not len(origin.loc[origin["ID"]==snp,pheno])==0 and (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (pd.isna(origin.loc[origin["ID"]==snp,pheno]).values[0]==False):
            count = 1 if (10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True)))<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result.loc[result["ID"]==snp,"counts"] = result.loc[result["ID"]==snp,"counts"] + count
result["counts"] = result["counts"]/num_perm
result.to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/"+pheno+".perm.p.csv",index=False)
result

   CHROM     GENPOS                 ID     f2257  counts
0     23  130129507   AIFM1.Mask2.0.01  0.071084    <NA>
1     23  108156906  COL4A6.Mask2.0.01  0.429358    <NA>
2     23   83508225  POU3F4.Mask2.0.01  0.024993   0.093
3     23  107628536   PRPS1.Mask2.0.01  0.343114    <NA>
4     23   21737489    SMPX.Mask2.0.01  0.000921  0.0022

In [59]:
pheno = "f2247_f2257"
num_perm = 5000
path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache"
list0 = os.listdir(path)
filelist = []
for file in list0:
    if file.endswith(pheno+".regenie.gz"):
        filelist.append(file)
sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
result = origin[["CHROM","GENPOS","ID",pheno]].copy()
result.loc[result["ID"].isin(sigsnp),"counts"]=0
result.loc[~result["ID"].isin(sigsnp),"counts"]=pd.NA
for file in filelist:
    data=pd.read_csv(os.path.join(path, file),header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if not len(origin.loc[origin["ID"]==snp,pheno])==0 and (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (pd.isna(origin.loc[origin["ID"]==snp,pheno]).values[0]==False):
            count = 1 if (10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True)))<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result.loc[result["ID"]==snp,"counts"] = result.loc[result["ID"]==snp,"counts"] + count
result["counts"] = result["counts"]/num_perm
result.to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/"+pheno+".perm.p.csv",index=False)
result

   CHROM     GENPOS                 ID  f2247_f2257  counts
0     23  130129507   AIFM1.Mask2.0.01     0.076015    <NA>
1     23  108156906  COL4A6.Mask2.0.01     0.734177    <NA>
2     23   83508225  POU3F4.Mask2.0.01     0.286156    <NA>
3     23  107628536   PRPS1.Mask2.0.01     0.380426    <NA>
4     23   21737489    SMPX.Mask2.0.01     0.000830  0.0002

### Burden all traits

In [12]:
pheno = "f3393"
sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
result1 = origin[["CHROM","GENPOS","ID",pheno]].copy()
result1.loc[result1["ID"].isin(sigsnp),"counts"]=0
result1.loc[~result1["ID"].isin(sigsnp),"counts"]=pd.NA
pheno = "f2247"
sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
result2 = origin[["CHROM","GENPOS","ID",pheno]].copy()
result2.loc[result2["ID"].isin(sigsnp),"counts"]=0
result2.loc[~result2["ID"].isin(sigsnp),"counts"]=pd.NA
pheno = "f2257"
sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
result3 = origin[["CHROM","GENPOS","ID",pheno]].copy()
result3.loc[result3["ID"].isin(sigsnp),"counts"]=0
result3.loc[~result3["ID"].isin(sigsnp),"counts"]=pd.NA
pheno = "f2247_f2257"
sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
result4 = origin[["CHROM","GENPOS","ID",pheno]].copy()
result4.loc[result4["ID"].isin(sigsnp),"counts"]=0
result4.loc[~result4["ID"].isin(sigsnp),"counts"]=pd.NA
for i in range(1,5000):
    pheno = "f3393"
    sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
    path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache/permutation."+ str(i) +"_burden_"+ pheno +".regenie.gz"
    data=pd.read_csv(path,header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")

    if (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False):
        p1 = 10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))
    else:
        p1 = pd.NA
        
    pheno = "f2247"
    sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
    path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache/permutation."+ str(i) +"_burden_"+ pheno +".regenie.gz"
    data=pd.read_csv(path,header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")

    if (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False):
        p2 = 10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))
    else:
        p2 = pd.NA
        
    pheno = "f2257"
    sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
    path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache/permutation."+ str(i) +"_burden_"+ pheno +".regenie.gz"
    data=pd.read_csv(path,header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")

    if (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False):
        p3 = 10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))
    else:
        p3 = pd.NA
        
    pheno = "f2247_f2257"
    sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
    path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache/permutation."+ str(i) +"_burden_"+ pheno +".regenie.gz"
    data=pd.read_csv(path,header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")

    if (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False):
        p4 = 10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))
    else:
        p4 = pd.NA
        
    minp = pd.DataFrame([p1,p2,p3,p4]).min(skipna=True).values[0]
    
    pheno = "f3393"
    sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
    path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache/permutation."+ str(i) +"_burden_"+ pheno +".regenie.gz"
    data=pd.read_csv(path,header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (len(origin.loc[origin["ID"]==snp,pheno])!=0):
            count = 1 if minp<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result1.loc[result1["ID"]==snp,"counts"] = result1.loc[result1["ID"]==snp,"counts"] + count
    pheno = "f2247"
    sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
    path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache/permutation."+ str(i) +"_burden_"+ pheno +".regenie.gz"
    data=pd.read_csv(path,header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (len(origin.loc[origin["ID"]==snp,pheno])!=0):
            count = 1 if minp<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result2.loc[result2["ID"]==snp,"counts"] = result2.loc[result2["ID"]==snp,"counts"] + count
    pheno = "f2257"
    sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
    path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache/permutation."+ str(i) +"_burden_"+ pheno +".regenie.gz"
    data=pd.read_csv(path,header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (len(origin.loc[origin["ID"]==snp,pheno])!=0):
            count = 1 if minp<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result3.loc[result3["ID"]==snp,"counts"] = result3.loc[result3["ID"]==snp,"counts"] + count
    pheno = "f2247_f2257"
    sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
    path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache/permutation."+ str(i) +"_burden_"+ pheno +".regenie.gz"
    data=pd.read_csv(path,header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (len(origin.loc[origin["ID"]==snp,pheno])!=0):
            count = 1 if minp<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result4.loc[result4["ID"]==snp,"counts"] = result4.loc[result4["ID"]==snp,"counts"] + count
result1.to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/all_traits/permutation.f3393.alltraits.perm.p.csv",index=False)
result2.to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/all_traits/permutation.f2247.alltraits.perm.p.csv",index=False)
result3.to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/all_traits/permutation.f2257.alltraits.perm.p.csv",index=False)
result4.to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/all_traits/permutation.f2247_f2257.alltraits.perm.p.csv",index=False)

## Try removing the numeber of NAs
### Burden each trait

In [2]:
## Original burden test results 
### Mask2.0.01
import pandas as pd
import os
data = pd.read_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/f3393/merged.phe_f3393.regenie_burden.snp_stats_original_columns.gz",compression = "gzip",sep="\t",header=0)
def find_target(row):
    for gene in ["PRPS1", "POU3F4", "SMPX", "AIFM1", "COL4A6"]:
        if gene in row["ID"]:
            return True
    return False
target = ["PRPS1.Mask2.0.01","POU3F4.Mask2.0.01","SMPX.Mask2.0.01","AIFM1.Mask2.0.01","COL4A6.Mask2.0.01"]
result = data[data["ID"].isin(target)][["CHROM","GENPOS","ID"]].copy()
result = result.merge(data[["ID","LOG10P"]],left_on="ID",right_on="ID",how="inner")
result = result.rename(columns={"LOG10P":"f3393"})
result["f3393"] = 10**(-result[["f3393"]]) 
data = pd.read_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/f2247/merged.phe_f2247.regenie_burden.snp_stats_original_columns.gz",compression = "gzip",sep="\t",header=0)
result = result.merge(data[["ID","LOG10P"]],left_on="ID",right_on="ID",how="inner")
result = result.rename(columns={"LOG10P":"f2247"})
result["f2247"] = 10**(-result[["f2247"]]) 
data = pd.read_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/f2257/merged.phe_f2257.regenie_burden.snp_stats_original_columns.gz",compression = "gzip",sep="\t",header=0)
result = result.merge(data[["ID","LOG10P"]],left_on="ID",right_on="ID",how="inner")
result = result.rename(columns={"LOG10P":"f2257"})
result["f2257"] = 10**(-result[["f2257"]]) 
data = pd.read_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/f2247_f2257/merged.phe_f2247_f2257.regenie_burden.snp_stats_original_columns.gz",compression = "gzip",sep="\t",header=0)
result = result.merge(data[["ID","LOG10P"]],left_on="ID",right_on="ID",how="inner")
result = result.rename(columns={"LOG10P":"f2247_f2257"})
result["f2247_f2257"] = 10**(-result[["f2247_f2257"]]) 
origin = result
origin

,CHROM,GENPOS,ID,f3393,f2247,f2257,f2247_f2257
0,23,130129507,AIFM1.Mask2.0.01,0.106222,0.141442,0.071084,0.076015
1,23,108156906,COL4A6.Mask2.0.01,0.106431,0.448032,0.429358,0.734177
2,23,83508225,POU3F4.Mask2.0.01,0.033939,0.126706,0.024993,0.286156
3,23,107628536,PRPS1.Mask2.0.01,0.618041,0.537899,0.343114,0.380426
4,23,21737489,SMPX.Mask2.0.01,0.153097,0.002454,0.000921,0.000830

In [3]:
pheno = "f3393"
num_perm = 5000
path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache"
list0 = os.listdir(path)
filelist = []
for file in list0:
    if file.endswith(pheno+".regenie.gz"):
        filelist.append(file)
sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
result = origin[["CHROM","GENPOS","ID",pheno]].copy()
result.loc[result["ID"].isin(sigsnp),"counts"]=0
result.loc[~result["ID"].isin(sigsnp),"counts"]=pd.NA
result.loc[result["ID"].isin(sigsnp),"nacounts"]=0
for file in filelist:
    data=pd.read_csv(os.path.join(path, file),header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if not len(origin.loc[origin["ID"]==snp,pheno])==0 and (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (pd.isna(origin.loc[origin["ID"]==snp,pheno]).values[0]==False):
            count = 1 if (10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True)))<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result.loc[result["ID"]==snp,"counts"] = result.loc[result["ID"]==snp,"counts"] + count
        if (pd.isna(origin.loc[origin["ID"]==snp,pheno]).values[0]==True):
            result.loc[origin["ID"]==snp,"nacounts"] = result.loc[origin["ID"]==snp,"nacounts"] + 1
result["counts"] = result["counts"]/(num_perm-result["nacounts"])
result

   CHROM     GENPOS                 ID     f3393  counts  nacounts
0     23  130129507   AIFM1.Mask2.0.01  0.106222    <NA>       NaN
1     23  108156906  COL4A6.Mask2.0.01  0.106431    <NA>       NaN
2     23   83508225  POU3F4.Mask2.0.01  0.033939  0.0226       0.0
3     23  107628536   PRPS1.Mask2.0.01  0.618041    <NA>       NaN
4     23   21737489    SMPX.Mask2.0.01  0.153097    <NA>       NaN

In [18]:
pheno = "f2247"
num_perm = 5000
path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache"
list0 = os.listdir(path)
filelist = []
for file in list0:
    if file.endswith(pheno+".regenie.gz"):
        filelist.append(file)
sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
result = origin[["CHROM","GENPOS","ID",pheno]].copy()
result.loc[result["ID"].isin(sigsnp),"counts"]=0
result.loc[~result["ID"].isin(sigsnp),"counts"]=pd.NA
result.loc[result["ID"].isin(sigsnp),"nacounts"]=0
for file in filelist:
    data=pd.read_csv(os.path.join(path, file),header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if not len(origin.loc[origin["ID"]==snp,pheno])==0 and (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (pd.isna(origin.loc[origin["ID"]==snp,pheno]).values[0]==False):
            count = 1 if (10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True)))<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result.loc[result["ID"]==snp,"counts"] = result.loc[result["ID"]==snp,"counts"] + count
        if (pd.isna(origin.loc[origin["ID"]==snp,pheno]).values[0]==True):
            result.loc[origin["ID"]==snp,"nacounts"] = result.loc[origin["ID"]==snp,"nacounts"] + 1
result["counts"] = result["counts"]/(num_perm-result["nacounts"])
result

   CHROM     GENPOS                 ID     f2247  counts  nacounts
0     23  130129507   AIFM1.Mask2.0.01  0.141442    <NA>       NaN
1     23  108156906  COL4A6.Mask2.0.01  0.448032    <NA>       NaN
2     23   83508225  POU3F4.Mask2.0.01  0.126706    <NA>       NaN
3     23  107628536   PRPS1.Mask2.0.01  0.537899    <NA>       NaN
4     23   21737489    SMPX.Mask2.0.01  0.002454  0.0012       0.0

In [5]:
pheno = "f2257"
num_perm = 5000
path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache"
list0 = os.listdir(path)
filelist = []
for file in list0:
    if file.endswith(pheno+".regenie.gz"):
        filelist.append(file)
sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
result = origin[["CHROM","GENPOS","ID",pheno]].copy()
result.loc[result["ID"].isin(sigsnp),"counts"]=0
result.loc[~result["ID"].isin(sigsnp),"counts"]=pd.NA
result.loc[result["ID"].isin(sigsnp),"nacounts"]=0
for file in filelist:
    data=pd.read_csv(os.path.join(path, file),header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if not len(origin.loc[origin["ID"]==snp,pheno])==0 and (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (pd.isna(origin.loc[origin["ID"]==snp,pheno]).values[0]==False):
            count = 1 if (10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True)))<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result.loc[result["ID"]==snp,"counts"] = result.loc[result["ID"]==snp,"counts"] + count
        if (pd.isna(origin.loc[origin["ID"]==snp,pheno]).values[0]==True):
            result.loc[origin["ID"]==snp,"nacounts"] = result.loc[origin["ID"]==snp,"nacounts"] + 1
result["counts"] = result["counts"]/(num_perm-result["nacounts"])
result

   CHROM     GENPOS                 ID     f2257  counts  nacounts
0     23  130129507   AIFM1.Mask2.0.01  0.071084    <NA>       NaN
1     23  108156906  COL4A6.Mask2.0.01  0.429358    <NA>       NaN
2     23   83508225  POU3F4.Mask2.0.01  0.024993   0.093       0.0
3     23  107628536   PRPS1.Mask2.0.01  0.343114    <NA>       NaN
4     23   21737489    SMPX.Mask2.0.01  0.000921  0.0022       0.0

In [6]:
pheno = "f2247_f2257"
num_perm = 5000
path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache"
list0 = os.listdir(path)
filelist = []
for file in list0:
    if file.endswith(pheno+".regenie.gz"):
        filelist.append(file)
sigsnp = origin.loc[origin[pheno]<=0.05,"ID"].to_list()
result = origin[["CHROM","GENPOS","ID",pheno]].copy()
result.loc[result["ID"].isin(sigsnp),"counts"]=0
result.loc[~result["ID"].isin(sigsnp),"counts"]=pd.NA
result.loc[result["ID"].isin(sigsnp),"nacounts"]=0
for file in filelist:
    data=pd.read_csv(os.path.join(path, file),header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if not len(origin.loc[origin["ID"]==snp,pheno])==0 and (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (pd.isna(origin.loc[origin["ID"]==snp,pheno]).values[0]==False):
            count = 1 if (10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True)))<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result.loc[result["ID"]==snp,"counts"] = result.loc[result["ID"]==snp,"counts"] + count
        if (pd.isna(origin.loc[origin["ID"]==snp,pheno]).values[0]==True):
            result.loc[origin["ID"]==snp,"nacounts"] = result.loc[origin["ID"]==snp,"nacounts"] + 1
result["counts"] = result["counts"]/(num_perm-result["nacounts"])
result

   CHROM     GENPOS                 ID  f2247_f2257  counts  nacounts
0     23  130129507   AIFM1.Mask2.0.01     0.076015    <NA>       NaN
1     23  108156906  COL4A6.Mask2.0.01     0.734177    <NA>       NaN
2     23   83508225  POU3F4.Mask2.0.01     0.286156    <NA>       NaN
3     23  107628536   PRPS1.Mask2.0.01     0.380426    <NA>       NaN
4     23   21737489    SMPX.Mask2.0.01     0.000830  0.0002       0.0

## Try adjusting for all five genes
### Burden each trait

In [2]:
## Original burden test results 
### Mask2.0.01
import pandas as pd
import os
data = pd.read_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/f3393/merged.phe_f3393.regenie_burden.snp_stats_original_columns.gz",compression = "gzip",sep="\t",header=0)
def find_target(row):
    for gene in ["PRPS1", "POU3F4", "SMPX", "AIFM1", "COL4A6"]:
        if gene in row["ID"]:
            return True
    return False
target = ["PRPS1.Mask2.0.01","POU3F4.Mask2.0.01","SMPX.Mask2.0.01","AIFM1.Mask2.0.01","COL4A6.Mask2.0.01"]
result = data[data["ID"].isin(target)][["CHROM","GENPOS","ID"]].copy()
result = result.merge(data[["ID","LOG10P"]],left_on="ID",right_on="ID",how="inner")
result = result.rename(columns={"LOG10P":"f3393"})
result["f3393"] = 10**(-result[["f3393"]]) 
data = pd.read_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/f2247/merged.phe_f2247.regenie_burden.snp_stats_original_columns.gz",compression = "gzip",sep="\t",header=0)
result = result.merge(data[["ID","LOG10P"]],left_on="ID",right_on="ID",how="inner")
result = result.rename(columns={"LOG10P":"f2247"})
result["f2247"] = 10**(-result[["f2247"]]) 
data = pd.read_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/f2257/merged.phe_f2257.regenie_burden.snp_stats_original_columns.gz",compression = "gzip",sep="\t",header=0)
result = result.merge(data[["ID","LOG10P"]],left_on="ID",right_on="ID",how="inner")
result = result.rename(columns={"LOG10P":"f2257"})
result["f2257"] = 10**(-result[["f2257"]]) 
data = pd.read_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/original/f2247_f2257/merged.phe_f2247_f2257.regenie_burden.snp_stats_original_columns.gz",compression = "gzip",sep="\t",header=0)
result = result.merge(data[["ID","LOG10P"]],left_on="ID",right_on="ID",how="inner")
result = result.rename(columns={"LOG10P":"f2247_f2257"})
result["f2247_f2257"] = 10**(-result[["f2247_f2257"]]) 
origin = result
origin

,CHROM,GENPOS,ID,f3393,f2247,f2257,f2247_f2257
0,23,130129507,AIFM1.Mask2.0.01,0.106222,0.141442,0.071084,0.076015
1,23,108156906,COL4A6.Mask2.0.01,0.106431,0.448032,0.429358,0.734177
2,23,83508225,POU3F4.Mask2.0.01,0.033939,0.126706,0.024993,0.286156
3,23,107628536,PRPS1.Mask2.0.01,0.618041,0.537899,0.343114,0.380426
4,23,21737489,SMPX.Mask2.0.01,0.153097,0.002454,0.000921,0.000830

In [3]:
pheno = "f3393"
num_perm = 5000
path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache"
list0 = os.listdir(path)
filelist = []
for file in list0:
    if file.endswith("burden_" + pheno+".regenie.gz"):
        filelist.append(file)
## Instead of using the significant genes, we use all five genes
sigsnp = origin["ID"].to_list()
result = origin[["CHROM","GENPOS","ID",pheno]].copy()
result.loc[result["ID"].isin(sigsnp),"counts"]=0
result.loc[~result["ID"].isin(sigsnp),"counts"]=pd.NA
for file in filelist:
    data=pd.read_csv(os.path.join(path, file),header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if not len(origin.loc[origin["ID"]==snp,pheno])==0 and (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (pd.isna(origin.loc[origin["ID"]==snp,pheno]).values[0]==False):
            count = 1 if (10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True)))<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result.loc[result["ID"]==snp,"counts"] = result.loc[result["ID"]==snp,"counts"] + count
result["counts"] = result["counts"]/num_perm
result.to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/"+pheno+".perm.p.csv",index=False)
result

   CHROM     GENPOS                 ID     f3393  counts
0     23  130129507   AIFM1.Mask2.0.01  0.106222  0.3826
1     23  108156906  COL4A6.Mask2.0.01  0.106431   0.383
2     23   83508225  POU3F4.Mask2.0.01  0.033939  0.1438
3     23  107628536   PRPS1.Mask2.0.01  0.618041  0.9958
4     23   21737489    SMPX.Mask2.0.01  0.153097  0.4958

In [20]:
pheno = "f2247"
num_perm = 5000
path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache"
list0 = os.listdir(path)
filelist = []
for file in list0:
    if file.endswith("burden_" + pheno+".regenie.gz"):
        filelist.append(file)
## Instead of using the significant genes, we use all five genes
sigsnp = origin["ID"].to_list()
result = origin[["CHROM","GENPOS","ID",pheno]].copy()
result.loc[result["ID"].isin(sigsnp),"counts"]=0
result.loc[~result["ID"].isin(sigsnp),"counts"]=pd.NA
for file in filelist:
    data=pd.read_csv(os.path.join(path, file),header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if not len(origin.loc[origin["ID"]==snp,pheno])==0 and (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (pd.isna(origin.loc[origin["ID"]==snp,pheno]).values[0]==False):
            count = 1 if (10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True)))<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result.loc[result["ID"]==snp,"counts"] = result.loc[result["ID"]==snp,"counts"] + count
result["counts"] = result["counts"]/num_perm
result.to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/"+pheno+".perm.p.csv",index=False)
result

   CHROM     GENPOS                 ID     f2247  counts
0     23  130129507   AIFM1.Mask2.0.01  0.141442   0.538
1     23  108156906  COL4A6.Mask2.0.01  0.448032  0.9528
2     23   83508225  POU3F4.Mask2.0.01  0.126706     0.5
3     23  107628536   PRPS1.Mask2.0.01  0.537899  0.9812
4     23   21737489    SMPX.Mask2.0.01  0.002454  0.0096

In [19]:
pheno = "f2257"
num_perm = 5000
path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache"
list0 = os.listdir(path)
filelist = []
for file in list0:
    if file.endswith("burden_" + pheno+".regenie.gz"):
        filelist.append(file)
## Instead of using the significant genes, we use all five genes
sigsnp = origin["ID"].to_list()
result = origin[["CHROM","GENPOS","ID",pheno]].copy()
result.loc[result["ID"].isin(sigsnp),"counts"]=0
result.loc[~result["ID"].isin(sigsnp),"counts"]=pd.NA
for file in filelist:
    data=pd.read_csv(os.path.join(path, file),header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if not len(origin.loc[origin["ID"]==snp,pheno])==0 and (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (pd.isna(origin.loc[origin["ID"]==snp,pheno]).values[0]==False):
            count = 1 if (10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True)))<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result.loc[result["ID"]==snp,"counts"] = result.loc[result["ID"]==snp,"counts"] + count
result["counts"] = result["counts"]/num_perm
result.to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/"+pheno+".perm.p.csv",index=False)
result

   CHROM     GENPOS                 ID     f2257  counts
0     23  130129507   AIFM1.Mask2.0.01  0.071084  0.3028
1     23  108156906  COL4A6.Mask2.0.01  0.429358  0.9326
2     23   83508225  POU3F4.Mask2.0.01  0.024993  0.1124
3     23  107628536   PRPS1.Mask2.0.01  0.343114  0.8746
4     23   21737489    SMPX.Mask2.0.01  0.000921  0.0036

In [5]:
pheno = "f2247_f2257"
num_perm = 5000
path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache"
list0 = os.listdir(path)
filelist = []
for file in list0:
    if file.endswith("burden_" + pheno+".regenie.gz"):
        filelist.append(file)
## Instead of using the significant genes, we use all five genes
sigsnp = origin["ID"].to_list()
result = origin[["CHROM","GENPOS","ID",pheno]].copy()
result.loc[result["ID"].isin(sigsnp),"counts"]=0
result.loc[~result["ID"].isin(sigsnp),"counts"]=pd.NA
for file in filelist:
    data=pd.read_csv(os.path.join(path, file),header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if not len(origin.loc[origin["ID"]==snp,pheno])==0 and (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (pd.isna(origin.loc[origin["ID"]==snp,pheno]).values[0]==False):
            count = 1 if (10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True)))<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result.loc[result["ID"]==snp,"counts"] = result.loc[result["ID"]==snp,"counts"] + count
result["counts"] = result["counts"]/num_perm
result.to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/"+pheno+".perm.p.csv",index=False)
result

   CHROM     GENPOS                 ID  f2247_f2257  counts
0     23  130129507   AIFM1.Mask2.0.01     0.076015  0.3252
1     23  108156906  COL4A6.Mask2.0.01     0.734177  0.9994
2     23   83508225  POU3F4.Mask2.0.01     0.286156    0.82
3     23  107628536   PRPS1.Mask2.0.01     0.380426   0.914
4     23   21737489    SMPX.Mask2.0.01     0.000830  0.0032

### Burden all traits

In [7]:
pheno = "f3393"
sigsnp = origin["ID"].to_list()
result1 = origin[["CHROM","GENPOS","ID",pheno]].copy()
result1.loc[result1["ID"].isin(sigsnp),"counts"]=0
result1.loc[~result1["ID"].isin(sigsnp),"counts"]=pd.NA
pheno = "f2247"
sigsnp = origin["ID"].to_list()
result2 = origin[["CHROM","GENPOS","ID",pheno]].copy()
result2.loc[result2["ID"].isin(sigsnp),"counts"]=0
result2.loc[~result2["ID"].isin(sigsnp),"counts"]=pd.NA
pheno = "f2257"
sigsnp = origin["ID"].to_list()
result3 = origin[["CHROM","GENPOS","ID",pheno]].copy()
result3.loc[result3["ID"].isin(sigsnp),"counts"]=0
result3.loc[~result3["ID"].isin(sigsnp),"counts"]=pd.NA
pheno = "f2247_f2257"
sigsnp = origin["ID"].to_list()
result4 = origin[["CHROM","GENPOS","ID",pheno]].copy()
result4.loc[result4["ID"].isin(sigsnp),"counts"]=0
result4.loc[~result4["ID"].isin(sigsnp),"counts"]=pd.NA
for i in range(1,5000):
    pheno = "f3393"
    sigsnp = origin["ID"].to_list()
    path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache/permutation."+ str(i) +"_burden_"+ pheno +".regenie.gz"
    data=pd.read_csv(path,header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")

    if (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False):
        p1 = 10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))
    else:
        p1 = pd.NA
        
    pheno = "f2247"
    sigsnp = origin["ID"].to_list()
    path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache/permutation."+ str(i) +"_burden_"+ pheno +".regenie.gz"
    data=pd.read_csv(path,header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")

    if (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False):
        p2 = 10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))
    else:
        p2 = pd.NA
        
    pheno = "f2257"
    sigsnp = origin["ID"].to_list()
    path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache/permutation."+ str(i) +"_burden_"+ pheno +".regenie.gz"
    data=pd.read_csv(path,header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")

    if (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False):
        p3 = 10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))
    else:
        p3 = pd.NA
        
    pheno = "f2247_f2257"
    sigsnp = origin["ID"].to_list()
    path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache/permutation."+ str(i) +"_burden_"+ pheno +".regenie.gz"
    data=pd.read_csv(path,header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")

    if (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False):
        p4 = 10**(-data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))
    else:
        p4 = pd.NA
        
    minp = pd.DataFrame([p1,p2,p3,p4]).min(skipna=True).values[0]  ## For all five genes and four trait, it's basically the smallest p among the 5*4 matrix
    
    pheno = "f3393"
    sigsnp = origin["ID"].to_list()
    path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache/permutation."+ str(i) +"_burden_"+ pheno +".regenie.gz"
    data=pd.read_csv(path,header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (len(origin.loc[origin["ID"]==snp,pheno])!=0):
            count = 1 if minp<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result1.loc[result1["ID"]==snp,"counts"] = result1.loc[result1["ID"]==snp,"counts"] + count
    pheno = "f2247"
    sigsnp = origin["ID"].to_list()
    path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache/permutation."+ str(i) +"_burden_"+ pheno +".regenie.gz"
    data=pd.read_csv(path,header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (len(origin.loc[origin["ID"]==snp,pheno])!=0):
            count = 1 if minp<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result2.loc[result2["ID"]==snp,"counts"] = result2.loc[result2["ID"]==snp,"counts"] + count
    pheno = "f2257"
    sigsnp = origin["ID"].to_list()
    path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache/permutation."+ str(i) +"_burden_"+ pheno +".regenie.gz"
    data=pd.read_csv(path,header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (len(origin.loc[origin["ID"]==snp,pheno])!=0):
            count = 1 if minp<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result3.loc[result3["ID"]==snp,"counts"] = result3.loc[result3["ID"]==snp,"counts"] + count
    pheno = "f2247_f2257"
    sigsnp = origin["ID"].to_list()
    path = "/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/each_trait/cache/permutation."+ str(i) +"_burden_"+ pheno +".regenie.gz"
    data=pd.read_csv(path,header=0, delim_whitespace=True, quotechar='"', comment='#',compression="gzip")
    for snp in sigsnp:
        if (pd.isna(data.loc[data["ID"].isin(sigsnp),"LOG10P"].max(skipna=True))==False) and (len(origin.loc[origin["ID"]==snp,pheno])!=0):
            count = 1 if minp<=origin.loc[origin["ID"]==snp,pheno].values[0] else 0
            result4.loc[result4["ID"]==snp,"counts"] = result4.loc[result4["ID"]==snp,"counts"] + count
result1.to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/all_traits/permutation.f3393.alltraits.perm.p.csv",index=False)
result2.to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/all_traits/permutation.f2247.alltraits.perm.p.csv",index=False)
result3.to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/all_traits/permutation.f2257.alltraits.perm.p.csv",index=False)
result4.to_csv("/mnt/vast/hpc/csg/en2509/exome/BurdenTest/permutation/regenie_burden/all_traits/permutation.f2247_f2257.alltraits.perm.p.csv",index=False)
result1

   CHROM     GENPOS                 ID     f3393  counts
0     23  130129507   AIFM1.Mask2.0.01  0.106222  3940.0
1     23  108156906  COL4A6.Mask2.0.01  0.106431  3944.0
2     23   83508225  POU3F4.Mask2.0.01  0.033939  1877.0
3     23  107628536   PRPS1.Mask2.0.01  0.618041  4999.0
4     23   21737489    SMPX.Mask2.0.01  0.153097  4469.0

In [8]:
result2

   CHROM     GENPOS                 ID     f2247  counts
0     23  130129507   AIFM1.Mask2.0.01  0.141442  4374.0
1     23  108156906  COL4A6.Mask2.0.01  0.448032  4999.0
2     23   83508225  POU3F4.Mask2.0.01  0.126706  4206.0
3     23  107628536   PRPS1.Mask2.0.01  0.537899  4999.0
4     23   21737489    SMPX.Mask2.0.01  0.002454   162.0

In [9]:
result3

   CHROM     GENPOS                 ID     f2257  counts
0     23  130129507   AIFM1.Mask2.0.01  0.071084  3246.0
1     23  108156906  COL4A6.Mask2.0.01  0.429358  4996.0
2     23   83508225  POU3F4.Mask2.0.01  0.024993  1455.0
3     23  107628536   PRPS1.Mask2.0.01  0.343114  4978.0
4     23   21737489    SMPX.Mask2.0.01  0.000921    59.0

In [10]:
result4

   CHROM     GENPOS                 ID  f2247_f2257  counts
0     23  130129507   AIFM1.Mask2.0.01     0.076015  3371.0
1     23  108156906  COL4A6.Mask2.0.01     0.734177  4999.0
2     23   83508225  POU3F4.Mask2.0.01     0.286156  4942.0
3     23  107628536   PRPS1.Mask2.0.01     0.380426  4992.0
4     23   21737489    SMPX.Mask2.0.01     0.000830    55.0