# Regenie file is in HG38 and bgen file is in HG19, so need to liftover regenie file to HG19 to see if all the regenie snps are in the bgen file prior to extraction to determine LD
* use Liftover Pipeline by Yin https://github.com/changebio/bioworkflows/blob/master/GWAS/liftover.ipynb

sos run liftover.ipynb --input_file /mnt/mfs/statgen/bst2126/pleiotropy/JAZF1_sum/asthma_PC10_step2_imp.regenie_ASTHMA.regenie --output_file asthma_regenie_lifted_to_hg19 --cwd /mnt/mfs/statgen/bst2126/pleiotropy/JAZF1_sum --fr hg38 --to hg19

## Prepare the files in Sumstat format before liftover

In [25]:
import pandas as pd

In [26]:
# ASTHMA: /home/yl2385/work/21fall/220110_regenie_asthma_rerun/asthma_PC10_step2_imp.regenie_ASTHMA.regenie
# T2D: /home/yl2385/work/21fall/220110_regenie_T2D_rerun/T2D_PC10_step2_imp.regenie_T2D.regenie
# WC: /home/yl2385/work/21fall/220110_regenie_WC_rerun/WC_PC10_step2_imp.regenie_WAISTcirc_invranknorm.regenie

# asthma data
asthma_regenie = pd.read_csv("/mnt/mfs/statgen/bst2126/pleiotropy/JAZF1_sum/asthma_PC10_step2_imp.regenie_ASTHMA.regenie", sep=" ")

# t2d data
t2d_regenie = pd.read_csv("/mnt/mfs/statgen/bst2126/pleiotropy/JAZF1_sum/T2D_PC10_step2_imp.regenie_T2D.regenie", sep=" ")

# waist circumference data
waist_regenie = pd.read_csv("/mnt/mfs/statgen/bst2126/pleiotropy/JAZF1_sum/WC_PC10_step2_imp.regenie_WAISTcirc_invranknorm.regenie", sep=" ")


# subsetting regenie data to only keep information within jazf1 region - 7 27868573 28273990
# also only keeping necessary columns for analysis
asthma_regenie = asthma_regenie[(asthma_regenie["CHROM"] == 7) & (asthma_regenie["GENPOS"] >= 27868573) & (asthma_regenie["GENPOS"] <= 28273990)][["CHROM", "GENPOS", "ID", "ALLELE0", "ALLELE1", "A1FREQ", "N", "BETA", "SE", "LOG10P"]]
t2d_regenie = t2d_regenie[(t2d_regenie["CHROM"] == 7) & (t2d_regenie["GENPOS"] >= 27868573) & (t2d_regenie["GENPOS"] <= 28273990)][["CHROM", "GENPOS", "ID", "ALLELE0", "ALLELE1", "A1FREQ", "N", "BETA", "SE", "LOG10P"]]
waist_regenie = waist_regenie[(waist_regenie["CHROM"] == 7) & (waist_regenie["GENPOS"] >= 27868573) & (waist_regenie["GENPOS"] <= 28273990)][["CHROM", "GENPOS", "ID", "ALLELE0", "ALLELE1", "A1FREQ", "N", "BETA", "SE", "LOG10P"]]

In [27]:
asthma_regenie

,CHROM,GENPOS,ID,ALLELE0,ALLELE1,A1FREQ,N,BETA,SE,LOG10P
6069486,7,27869098,rs545409685,C,T,0.997340,339345,0.116773,0.071129,0.997184
6069487,7,27869261,7:27869261_CAGTA_C,C,CAGTA,0.998498,339345,0.036830,0.098431,0.149797
6069488,7,27869377,rs73075348,G,A,0.943372,339345,-0.000204,0.015226,0.004665
6069489,7,27869782,rs6948467,A,G,0.607234,339345,-0.002206,0.007223,0.119179
6069490,7,27869794,rs73075354,G,C,0.883803,339345,0.012311,0.011001,0.579898
...,...,...,...,...,...,...,...,...,...,...
6071548,7,28273623,7:28273623_TTTCCTTCCTTCC_T,T,TTTCCTTCCTTCC,0.842749,339345,0.000601,0.009892,0.021555
6071549,7,28273697,rs188426589,A,T,0.987408,339345,-0.004086,0.031982,0.046563
6071550,7,28273719,rs6944995,G,T,0.146693,339345,0.006399,0.009963,0.283409
6071551,7,28273829,rs192297723,C,A,0.988365,339345,0.013026,0.035082,0.148496
6071552,7,28273986,rs849313,C,T,0.190610,339345,0.011676,0.008962,0.715254

In [28]:
t2d_regenie

,CHROM,GENPOS,ID,ALLELE0,ALLELE1,A1FREQ,N,BETA,SE,LOG10P
6070158,7,27869098,rs545409685,C,T,0.997337,336074,0.038626,0.100036,0.155268
6070159,7,27869261,7:27869261_CAGTA_C,C,CAGTA,0.998492,336074,0.108386,0.140165,0.357178
6070160,7,27869377,rs73075348,G,A,0.943307,336074,0.016225,0.021522,0.345893
6070161,7,27869782,rs6948467,A,G,0.607261,336074,-0.020544,0.010241,1.348310
6070162,7,27869794,rs73075354,G,C,0.883898,336074,0.038589,0.015628,1.868420
...,...,...,...,...,...,...,...,...,...,...
6072220,7,28273623,7:28273623_TTTCCTTCCTTCC_T,T,TTTCCTTCCTTCC,0.842757,336074,-0.007129,0.014019,0.213893
6072221,7,28273697,rs188426589,A,T,0.987404,336074,-0.013464,0.045338,0.115494
6072222,7,28273719,rs6944995,G,T,0.146537,336074,0.013798,0.014138,0.482690
6072223,7,28273829,rs192297723,C,A,0.988329,336074,-0.051344,0.049307,0.526178
6072224,7,28273986,rs849313,C,T,0.190446,336074,0.021089,0.012715,1.012320

In [29]:
waist_regenie

,CHROM,GENPOS,ID,ALLELE0,ALLELE1,A1FREQ,N,BETA,SE,LOG10P
6069968,7,27869098,rs545409685,C,T,0.997340,365499,0.000830,0.009980,0.029799
6069969,7,27869261,7:27869261_CAGTA_C,C,CAGTA,0.998506,365499,-0.018772,0.013917,0.751086
6069970,7,27869377,rs73075348,G,A,0.943390,365499,-0.002467,0.002139,0.604290
6069971,7,27869782,rs6948467,A,G,0.607228,365499,-0.002577,0.001015,1.953540
6069972,7,27869794,rs73075354,G,C,0.883827,365499,0.006933,0.001547,5.128300
...,...,...,...,...,...,...,...,...,...,...
6072031,7,28273623,7:28273623_TTTCCTTCCTTCC_T,T,TTTCCTTCCTTCC,0.842736,365499,-0.001481,0.001391,0.541901
6072032,7,28273697,rs188426589,A,T,0.987452,365499,-0.008732,0.004520,1.272780
6072033,7,28273719,rs6944995,G,T,0.146811,365499,0.003185,0.001400,1.640000
6072034,7,28273829,rs192297723,C,A,0.988319,365499,-0.002544,0.004923,0.218021
6072035,7,28273986,rs849313,C,T,0.190705,365499,0.004186,0.001260,3.048090

In [30]:
# sumdata format 
# from current regenie data need to calculate A0FREQ and PVAL

# A0FREQ
get_a0freq = lambda row: 1 - row["A1FREQ"]

asthma_regenie["A0FREQ"] = asthma_regenie.apply(get_a0freq, axis=1)
t2d_regenie["A0FREQ"] = t2d_regenie.apply(get_a0freq, axis=1)
waist_regenie["A0FREQ"] = waist_regenie.apply(get_a0freq, axis=1)

# PVAL
get_pval = lambda row: 10 ** (-row["LOG10P"])

asthma_regenie["PVAL"] = asthma_regenie.apply(get_pval, axis=1)
t2d_regenie["PVAL"] = t2d_regenie.apply(get_pval, axis=1)
waist_regenie["PVAL"] = waist_regenie.apply(get_pval, axis=1)

In [31]:
asthma_regenie

,CHROM,GENPOS,ID,ALLELE0,ALLELE1,A1FREQ,N,BETA,SE,LOG10P,A0FREQ,PVAL
6069486,7,27869098,rs545409685,C,T,0.997340,339345,0.116773,0.071129,0.997184,0.002660,0.100651
6069487,7,27869261,7:27869261_CAGTA_C,C,CAGTA,0.998498,339345,0.036830,0.098431,0.149797,0.001502,0.708277
6069488,7,27869377,rs73075348,G,A,0.943372,339345,-0.000204,0.015226,0.004665,0.056628,0.989316
6069489,7,27869782,rs6948467,A,G,0.607234,339345,-0.002206,0.007223,0.119179,0.392766,0.760013
6069490,7,27869794,rs73075354,G,C,0.883803,339345,0.012311,0.011001,0.579898,0.116197,0.263089
...,...,...,...,...,...,...,...,...,...,...,...,...
6071548,7,28273623,7:28273623_TTTCCTTCCTTCC_T,T,TTTCCTTCCTTCC,0.842749,339345,0.000601,0.009892,0.021555,0.157251,0.951580
6071549,7,28273697,rs188426589,A,T,0.987408,339345,-0.004086,0.031982,0.046563,0.012592,0.898333
6071550,7,28273719,rs6944995,G,T,0.146693,339345,0.006399,0.009963,0.283409,0.853307,0.520704
6071551,7,28273829,rs192297723,C,A,0.988365,339345,0.013026,0.035082,0.148496,0.011635,0.710402
6071552,7,28273986,rs849313,C,T,0.190610,339345,0.011676,0.008962,0.715254,0.809390,0.192640

In [33]:
# keeping only relevant columns
asthma_regenie = asthma_regenie[["CHROM","GENPOS","ID", "ALLELE0", "ALLELE1", "A0FREQ", "BETA", "SE", "PVAL", "N"]]
t2d_regenie = t2d_regenie[["CHROM","GENPOS","ID", "ALLELE0", "ALLELE1", "A0FREQ", "BETA", "SE", "PVAL", "N"]]
waist_regenie = waist_regenie[["CHROM","GENPOS","ID", "ALLELE0", "ALLELE1", "A0FREQ", "BETA", "SE", "PVAL", "N"]]

In [34]:
asthma_regenie

,CHROM,GENPOS,ID,ALLELE0,ALLELE1,A0FREQ,BETA,SE,PVAL,N
6069486,7,27869098,rs545409685,C,T,0.002660,0.116773,0.071129,0.100651,339345
6069487,7,27869261,7:27869261_CAGTA_C,C,CAGTA,0.001502,0.036830,0.098431,0.708277,339345
6069488,7,27869377,rs73075348,G,A,0.056628,-0.000204,0.015226,0.989316,339345
6069489,7,27869782,rs6948467,A,G,0.392766,-0.002206,0.007223,0.760013,339345
6069490,7,27869794,rs73075354,G,C,0.116197,0.012311,0.011001,0.263089,339345
...,...,...,...,...,...,...,...,...,...,...
6071548,7,28273623,7:28273623_TTTCCTTCCTTCC_T,T,TTTCCTTCCTTCC,0.157251,0.000601,0.009892,0.951580,339345
6071549,7,28273697,rs188426589,A,T,0.012592,-0.004086,0.031982,0.898333,339345
6071550,7,28273719,rs6944995,G,T,0.853307,0.006399,0.009963,0.520704,339345
6071551,7,28273829,rs192297723,C,A,0.011635,0.013026,0.035082,0.710402,339345
6071552,7,28273986,rs849313,C,T,0.809390,0.011676,0.008962,0.192640,339345

In [35]:
# renaming columns in Sumstat format
asthma_regenie = asthma_regenie.rename(columns={"CHROM":"CHR", "GENPOS":"POS", "ID":"SNP", "ALLELE0":"A1", "ALLELE1":"A2", "A0FREQ":"A1FREQ", "BETA":"beta", "SE":"se", "PVAL":"p"})
t2d_regenie = t2d_regenie.rename(columns={"CHROM":"CHR", "GENPOS":"POS", "ID":"SNP", "ALLELE0":"A1", "ALLELE1":"A2", "A0FREQ":"A1FREQ", "BETA":"beta", "SE":"se", "PVAL":"p"})
waist_regenie = waist_regenie.rename(columns={"CHROM":"CHR", "GENPOS":"POS", "ID":"SNP", "ALLELE0":"A1", "ALLELE1":"A2", "A0FREQ":"A1FREQ", "BETA":"beta", "SE":"se", "PVAL":"p"})

In [36]:
asthma_regenie

,CHR,POS,SNP,A1,A2,A1FREQ,beta,se,p,N
6069486,7,27869098,rs545409685,C,T,0.002660,0.116773,0.071129,0.100651,339345
6069487,7,27869261,7:27869261_CAGTA_C,C,CAGTA,0.001502,0.036830,0.098431,0.708277,339345
6069488,7,27869377,rs73075348,G,A,0.056628,-0.000204,0.015226,0.989316,339345
6069489,7,27869782,rs6948467,A,G,0.392766,-0.002206,0.007223,0.760013,339345
6069490,7,27869794,rs73075354,G,C,0.116197,0.012311,0.011001,0.263089,339345
...,...,...,...,...,...,...,...,...,...,...
6071548,7,28273623,7:28273623_TTTCCTTCCTTCC_T,T,TTTCCTTCCTTCC,0.157251,0.000601,0.009892,0.951580,339345
6071549,7,28273697,rs188426589,A,T,0.012592,-0.004086,0.031982,0.898333,339345
6071550,7,28273719,rs6944995,G,T,0.853307,0.006399,0.009963,0.520704,339345
6071551,7,28273829,rs192297723,C,A,0.011635,0.013026,0.035082,0.710402,339345
6071552,7,28273986,rs849313,C,T,0.809390,0.011676,0.008962,0.192640,339345

In [37]:
t2d_regenie

,CHR,POS,SNP,A1,A2,A1FREQ,beta,se,p,N
6070158,7,27869098,rs545409685,C,T,0.002663,0.038626,0.100036,0.699410,336074
6070159,7,27869261,7:27869261_CAGTA_C,C,CAGTA,0.001508,0.108386,0.140165,0.439362,336074
6070160,7,27869377,rs73075348,G,A,0.056693,0.016225,0.021522,0.450928,336074
6070161,7,27869782,rs6948467,A,G,0.392739,-0.020544,0.010241,0.044843,336074
6070162,7,27869794,rs73075354,G,C,0.116102,0.038589,0.015628,0.013539,336074
...,...,...,...,...,...,...,...,...,...,...
6072220,7,28273623,7:28273623_TTTCCTTCCTTCC_T,T,TTTCCTTCCTTCC,0.157243,-0.007129,0.014019,0.611093,336074
6072221,7,28273697,rs188426589,A,T,0.012596,-0.013464,0.045338,0.766489,336074
6072222,7,28273719,rs6944995,G,T,0.853463,0.013798,0.014138,0.329086,336074
6072223,7,28273829,rs192297723,C,A,0.011671,-0.051344,0.049307,0.297730,336074
6072224,7,28273986,rs849313,C,T,0.809554,0.021089,0.012715,0.097203,336074

In [38]:
waist_regenie

,CHR,POS,SNP,A1,A2,A1FREQ,beta,se,p,N
6069968,7,27869098,rs545409685,C,T,0.002660,0.000830,0.009980,0.933687,365499
6069969,7,27869261,7:27869261_CAGTA_C,C,CAGTA,0.001494,-0.018772,0.013917,0.177384,365499
6069970,7,27869377,rs73075348,G,A,0.056610,-0.002467,0.002139,0.248720,365499
6069971,7,27869782,rs6948467,A,G,0.392772,-0.002577,0.001015,0.011129,365499
6069972,7,27869794,rs73075354,G,C,0.116173,0.006933,0.001547,0.000007,365499
...,...,...,...,...,...,...,...,...,...,...
6072031,7,28273623,7:28273623_TTTCCTTCCTTCC_T,T,TTTCCTTCCTTCC,0.157264,-0.001481,0.001391,0.287144,365499
6072032,7,28273697,rs188426589,A,T,0.012548,-0.008732,0.004520,0.053361,365499
6072033,7,28273719,rs6944995,G,T,0.853189,0.003185,0.001400,0.022909,365499
6072034,7,28273829,rs192297723,C,A,0.011681,-0.002544,0.004923,0.605312,365499
6072035,7,28273986,rs849313,C,T,0.809295,0.004186,0.001260,0.000895,365499

In [39]:
# Save sumstat format files to be lifted

asthma_regenie.to_csv("/mnt/mfs/statgen/bst2126/pleiotropy/JAZF1_sum/asthma_regenie_sumstat_jazf1", sep=" ", index=False)
t2d_regenie.to_csv("/mnt/mfs/statgen/bst2126/pleiotropy/JAZF1_sum/t2d_regenie_sumstat_jazf1", sep=" ", index=False)
waist_regenie.to_csv("/mnt/mfs/statgen/bst2126/pleiotropy/JAZF1_sum/waist_regenie_sumstat_jazf1", sep=" ", index=False)

In [ ]:

git clone https://github.com/changebio/bioworkflows.git
sos run bioworkflows/GWAS/liftover.ipynb --input_file /mnt/mfs/statgen/bst2126/pleiotropy/JAZF1_sum/asthma_regenie_sumstat_jazf1 --output_file asthma_regenie_jazf1_lifted_to_hg19 --cwd /mnt/mfs/hgrcgrid/bst2126/pleiotropy/JAZF1_sum